//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class Obra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Obra()
        {
            this.EmpleadoProyecto = new HashSet<EmpleadoProyecto>();
            this.Etapa = new HashSet<Etapa>();
            this.EtapaProyecto = new HashSet<EtapaProyecto>();
            this.Gasto = new HashSet<Gasto>();
            this.ObraMateriales = new HashSet<ObraMateriales>();
        }
        [DataMember]
        public int IDObra { get; set; }
        [DataMember]
        public string Nombre { get; set; }
        [DataMember]
        public int IDUbicacion { get; set; }
        [DataMember]
        public int Habitaciones { get; set; }
        [DataMember]
        public int Baños { get; set; }
        [DataMember]
        public int Pisos { get; set; }
        [DataMember]
        public int MetrosCuadradosConstruccion { get; set; }
        [DataMember]
        public int MetrosCuadradosLote { get; set; }
        [DataMember]
        public int IDIngeniero1 { get; set; }
        [DataMember]
        public Nullable<int> IDIngeniero2 { get; set; }
        [DataMember]
        public Nullable<int> IDIngeniero3 { get; set; }
        [DataMember]
        public int IDCliente { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpleadoProyecto> EmpleadoProyecto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Etapa> Etapa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EtapaProyecto> EtapaProyecto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gasto> Gasto { get; set; }
        public virtual Ingeniero Ingeniero { get; set; }
        public virtual Ubicacion Ubicacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObraMateriales> ObraMateriales { get; set; }
    }
}
