//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEConstruye_API
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class EtapaProyecto
    {
        [DataMember]
        public int IDEtapaProyecto { get; set; }
        [DataMember]
        public int IDObra { get; set; }
        [DataMember]
        public int IDEtapa { get; set; }
        [DataMember]
        public System.DateTime FechaInicio { get; set; }
        [DataMember]
        public Nullable<System.DateTime> FechaFin { get; set; }
        [DataMember]
        public Nullable<int> Presupuesto { get; set; }
    
        public virtual Etapa Etapa { get; set; }
        public virtual Obra Obra { get; set; }
    }
}
