//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEConstruye_API
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class Gasto
    {
        [DataMember]
        public int IDGasto { get; set; }
        [DataMember]
        public int IDObra { get; set; }
        [DataMember]
        public int Proveedor { get; set; }
        [DataMember]
        public int IDFactura { get; set; }
        [DataMember]
        public string Foto { get; set; }
    
        public virtual Factura Factura { get; set; }
        public virtual Obra Obra { get; set; }
        public virtual Proveedor Proveedor1 { get; set; }
    }
}
