//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEConstruye_API
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class Obra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Obra()
        {
            this.EmpleadoObra = new HashSet<EmpleadoObra>();
            this.EtapaMateriales = new HashSet<EtapaMateriales>();
            this.EtapaObra = new HashSet<EtapaObra>();
            this.Factura = new HashSet<Factura>();
            this.Gasto = new HashSet<Gasto>();
        }

        [DataMember]
        public int IDObra { get; set; }
        [DataMember]
        public string Nombre { get; set; }
        [DataMember]
        public int Ubicacion { get; set; }
        [DataMember]
        public int Habitaciones { get; set; }
        [DataMember]
        public int Banos { get; set; }
        [DataMember]
        public int Pisos { get; set; }
        [DataMember]
        public int AreaConstruccion { get; set; }
        [DataMember]
        public int AreaLote { get; set; }
        [DataMember]
        public int IDIngeniero1 { get; set; }
        [DataMember]
        public Nullable<int> IDIngeniero2 { get; set; }
        [DataMember]
        public Nullable<int> IDIngeniero3 { get; set; }
        [DataMember]
        public string IDCliente { get; set; }

        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpleadoObra> EmpleadoObra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EtapaMateriales> EtapaMateriales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EtapaObra> EtapaObra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Factura> Factura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gasto> Gasto { get; set; }
        public virtual Ingeniero Ingeniero { get; set; }
        public virtual Ingeniero Ingeniero1 { get; set; }
        public virtual Ingeniero Ingeniero2 { get; set; }
        public virtual Ubicacion Ubicacion1 { get; set; }
    }
}
