//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientDataAccess
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class Gasto
    {
        [DataMember]
        public int IDGasto { get; set; }
        [DataMember]
        public int IDObra { get; set; }
        [DataMember]
        public Nullable<int> IDProveedor { get; set; }
        [DataMember]
        public Nullable<int> IDFactura { get; set; }
        [DataMember]
        public byte[] Foto { get; set; }
    
        public virtual Obra Obra { get; set; }
    }
}
